name: macos

on: [push, pull_request]

env:
  CXXFLAGS: "-Werror -Wshadow -Woverloaded-virtual -Wextra-semi -Wunreachable-code -fno-operator-names -Wno-pass-failed"

jobs:
  # Build all tutorials
  tests-macos:
    name: AppleClang@15.0 GFortran@15.1 [tutorials]
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: Dependencies
      run: .github/workflows/dependencies/dependencies_mac.sh
    - name: Build & Install
      run: |
        export LIBRARY_PATH=/opt/homebrew/opt/gcc/lib/gcc/current/

        cd ExampleCodes
        cmake -S . -B build             \
            -DBUILD_SHARED_LIBS=ON      \
            -DCMAKE_BUILD_TYPE=Debug    \
            -DCMAKE_VERBOSE_MAKEFILE=ON \
            -DAMReX_LINEAR_SOLVERS=ON     \
            -DAMReX_FORTRAN=ON          \
            -DAMReX_FORTRAN_INTERFACES=ON \
            -DAMReX_EB=ON                 \
            -DAMReX_PARTICLES=ON        \
            -DCMAKE_Fortran_COMPILER=$(which gfortran-15)   \
            -DCMAKE_CXX_COMPILER_LAUNCHER=$(which ccache)
        cmake --build build --parallel 2

        cmake -S . -B build             \
            -DCMAKE_BUILD_TYPE=Debug    \
            -DCMAKE_VERBOSE_MAKEFILE=ON \
            -DAMReX_LINEAR_SOLVERS=ON     \
            -DAMReX_FORTRAN=ON          \
            -DAMReX_FORTRAN_INTERFACES=ON \
            -DAMReX_EB=ON                 \
            -DAMReX_PARTICLES=ON        \
            -DCMAKE_Fortran_COMPILER=$(which gfortran-15)   \
            -DCMAKE_CXX_COMPILER_LAUNCHER=$(which ccache)
        cmake --build build --parallel 2

